window.fifaRank = [
  { rank: 1, team: "Argentina" },
  { rank: 2, team: "Spain" },
  { rank: 3, team: "France" },
  { rank: 4, team: "England" },
  { rank: 5, team: "Portugal" },
  { rank: 6, team: "Brazil" },
  { rank: 7, team: "Morocco" },
  { rank: 8, team: "Netherlands" },
  { rank: 9, team: "Belgium" },
  { rank: 10, team: "Germany" },
  { rank: 11, team: "Croatia" },
  { rank: 13, team: "Colombia" },
  { rank: 14, team: "Mexico" },
  { rank: 15, team: "Senegal" },
  { rank: 16, team: "Uruguay" },
  { rank: 17, team: "USA" },
  { rank: 18, team: "Japan" },
  { rank: 19, team: "Switzerland" },
  { rank: 20, team: "IR Iran" },
  { rank: 22, team: "Türkiye" },
  { rank: 23, team: "Ecuador" },
  { rank: 24, team: "Austria" },
  { rank: 25, team: "Korea Republic" },
  { rank: 27, team: "Australia" },
  { rank: 28, team: "Algeria" },
  { rank: 29, team: "Egypt" },
  { rank: 30, team: "Canada" },
  { rank: 31, team: "Norway" },
  { rank: 33, team: "Côte d'Ivoire" },
  { rank: 34, team: "Panama" },
  { rank: 38, team: "Sweden" },
  { rank: 40, team: "Czechia" },
  { rank: 41, team: "Paraguay" },
  { rank: 42, team: "Scotland" },
  { rank: 45, team: "Tunisia" },
  { rank: 46, team: "Congo DR" },
  { rank: 50, team: "Uzbekistan" },
  { rank: 56, team: "Qatar" },
  { rank: 57, team: "Iraq" },
  { rank: 60, team: "South Africa" },
  { rank: 61, team: "Saudi Arabia" },
  { rank: 63, team: "Jordan" },
  { rank: 64, team: "Bosnia and Herzegovina" },
  { rank: 67, team: "Cabo Verde" },
  { rank: 73, team: "Ghana" },
  { rank: 82, team: "Curaçao" },
  { rank: 83, team: "Haiti" },
  { rank: 85, team: "New Zealand" }
];